version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-latest
      - test-1.11
      - test-1.10
      - test-1.9
      - test-1.8
jobs:
  test-latest: &test-template
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/immortal/logrotate
    steps:
      - checkout
      - run: go get
      - run: go test -race -v
  test-1.11:
    <<: *test-template
    docker:
      - image: circleci/golang:1.11
  test-1.10:
    <<: *test-template
    docker:
      - image: circleci/golang:1.10
  test-1.9:
    <<: *test-template
    docker:
      - image: circleci/golang:1.9
  test-1.8:
    <<: *test-template
    docker:
      - image: circleci/golang:1.8
